/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#88919d',
        'primary-fixed-dim': '#98cbff',
        'surface-variant': '#353437',
        'inverse-on-surface': '#303032',
        'on-primary-fixed': '#001d33',
        'surface-container': '#201f21',
        'on-secondary': '#003824',
        'on-secondary-fixed': '#002113',
        'on-tertiary-fixed': '#2a1700',
        'outline-variant': '#3f4852',
        'surface-container-lowest': '#0e0e10',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#004a77',
        'surface-dim': '#131315',
        'primary-container': '#00a3ff',
        'on-secondary-fixed-variant': '#005236',
        'on-surface': '#e5e1e4',
        'surface-bright': '#39393b',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-error-container': '#ffdad6',
        'surface-tint': '#98cbff',
        'on-tertiary-container': '#4c2d00',
        'surface-container-low': '#1b1b1d',
        background: '#131315',
        'on-secondary-container': '#00311f',
        'on-primary-container': '#00375a',
        'on-primary': '#003354',
        'secondary-fixed-dim': '#4edea3',
        'surface-container-highest': '#353437',
        'on-error': '#690005',
        'on-background': '#e5e1e4',
        'surface-container-high': '#2a2a2c',
        'on-tertiary-fixed-variant': '#653e00',
        'secondary-fixed': '#6ffbbe',
        'secondary-container': '#00a572',
        tertiary: '#ffb95f',
        secondary: '#4edea3',
        'on-surface-variant': '#bec7d4',
        surface: '#131315',
        'on-tertiary': '#472a00',
        error: '#ffb4ab',
        'inverse-surface': '#e5e1e4',
        'inverse-primary': '#00629d',
        'tertiary-container': '#da8b00',
        primary: '#98cbff',
        'primary-fixed': '#cfe5ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-padding': '24px',
        'stack-lg': '32px',
        unit: '4px',
        'stack-md': '16px',
        gutter: '16px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'label-caps': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-base': ['Inter'],
        'headline-md-mobile': ['Inter'],
        'data-mono-sm': ['JetBrains Mono'],
        'data-mono': ['JetBrains Mono'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-mono-sm': ['11px', { lineHeight: '16px', fontWeight: '400' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '450' }],
      },
      boxShadow: {
        'active-glow': '0 0 12px #00A3FF26',
        'success-glow': '0 0 12px rgba(78, 222, 163, 0.25)',
      },
    },
  },
  plugins: [],
}
