"""SentinelForge Phase 5 — Blue Agent Analyst & Detection Remediation Pipeline

Consumes detection outcomes generated by DetectionGapEvaluator, analyzes detection gaps,
derives evidence-backed candidate Sigma rules with immutable provenance, validates syntax
and false-positive immunity in a telemetry-only sandbox, and orchestrates authorized retesting
through the existing security boundaries.

SECURITY INVARIANTS:
- Blue Agent is UNTRUSTED.
- MUST NOT execute system commands directly.
- MUST NOT create SignedBlueprint objects or invoke BlueprintSigner.
- MUST NOT bypass ExperimentSafetyBoundary or PolicyEngine.
- MUST NOT manufacture RetestResult objects or directly transition ExerciseStateMachine to VERIFIED.
- All candidate rules MUST preserve x-sentinelforge provenance.
- Overly broad rules and false positives MUST be strictly rejected.
"""

from datetime import datetime, timezone
import logging
from typing import List, Optional, Tuple, Union
from uuid import UUID, uuid4

import yaml
from pydantic import BaseModel, Field

from sentinelforge.agents.red_agent import RedAgentPlanner, PlanResult
from sentinelforge.detection.evaluator import (
    ActionDetectionOutcome,
    DetectionGapEvaluator,
    ScenarioDetectionOutcome,
)
from sentinelforge.detection.normalizer import NormalizedEvent
from sentinelforge.detection.sigma_engine import DetectionOutcome, SigmaEngine
from sentinelforge.domain.action_ir import ActionIR
from sentinelforge.domain.experiment import (
    CandidateSigmaRule,
    RetestRequest,
    RetestResult,
    SecurityObjective,
    ValidationSandboxResult,
    ValidationSandboxStatus,
)
from sentinelforge.simulation.adapter import SimulationAdapter

logger = logging.getLogger(__name__)


class GapAnalysisResult(BaseModel):
    """Structured root cause analysis for a single detected gap action."""

    gap_id: str = Field(default_factory=lambda: str(uuid4()))
    scenario_id: str
    action_id: str
    technique_id: str
    original_outcome: str
    evidence_event_ids: List[str] = Field(default_factory=list)
    matched_rule_ids: List[str] = Field(default_factory=list)
    root_cause: str  # NO_TELEMETRY, NO_RULE_MATCH, UNRELATED_RULE_MATCH, INSUFFICIENT_TECHNIQUE_METADATA, INSUFFICIENT_RULE_COVERAGE
    reason: str
    analyzed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class BlueAgentAnalyst:
    """Blue Agent Analyst for analyzing detection gaps and generating evidence-backed candidate Sigma rules."""

    def analyze_gap(
        self,
        scenario_outcome: ScenarioDetectionOutcome,
        actions: Optional[List[ActionIR]] = None,
        db_session=None,
    ) -> List[GapAnalysisResult]:
        """Analyze a ScenarioDetectionOutcome and produce structured GapAnalysisResult objects."""
        results: List[GapAnalysisResult] = []
        action_map = {str(a.action_id): a for a in actions} if actions else {}

        for act_outcome in scenario_outcome.action_outcomes:
            outcome_str = (
                act_outcome.outcome.value
                if isinstance(act_outcome.outcome, DetectionOutcome)
                else str(act_outcome.outcome)
            )

            # Analyze only actions that failed detection
            if outcome_str == DetectionOutcome.DETECTED.value:
                continue

            action_id_str = str(act_outcome.action_id)
            tech_id = str(act_outcome.technique_id or "unknown").strip()
            action_ir = action_map.get(action_id_str)
            if action_ir and (not tech_id or tech_id == "unknown"):
                tech_id = str(action_ir.technique_id).strip()

            # Determine evidence-backed root cause
            if tech_id == "unknown" or not tech_id:
                root_cause = "INSUFFICIENT_TECHNIQUE_METADATA"
                reason = f"Action {action_id_str} lacks valid MITRE ATT&CK technique metadata"
            elif not act_outcome.evidence_event_ids:
                root_cause = "NO_TELEMETRY"
                reason = f"No telemetry events were captured for action {action_id_str} (technique {tech_id})"
            elif "unrelated" in act_outcome.reason.lower():
                root_cause = "UNRELATED_RULE_MATCH"
                reason = act_outcome.reason
            elif outcome_str in (DetectionOutcome.NOT_DETECTED.value, DetectionOutcome.DETECTION_GAP.value):
                root_cause = "NO_RULE_MATCH"
                reason = f"Telemetry observed for action {action_id_str}, but no Sigma rule matched technique {tech_id}"
            else:
                root_cause = "INSUFFICIENT_RULE_COVERAGE"
                reason = f"Incomplete detection rule coverage for technique {tech_id}"

            gap_res = GapAnalysisResult(
                scenario_id=str(scenario_outcome.scenario_id),
                action_id=action_id_str,
                technique_id=tech_id,
                original_outcome=outcome_str,
                evidence_event_ids=[str(e) for e in act_outcome.evidence_event_ids],
                matched_rule_ids=[str(m) for m in act_outcome.matched_rule_ids],
                root_cause=root_cause,
                reason=reason,
            )
            results.append(gap_res)

            if db_session:
                import json as json_lib
                from sentinelforge.db.models import DetectionGapRecord
                org_uuid = UUID(str(scenario_outcome.organization_id)) if scenario_outcome.organization_id else UUID(int=0)
                rec = DetectionGapRecord(
                    id=UUID(gap_res.gap_id),
                    organization_id=org_uuid,
                    scenario_id=UUID(gap_res.scenario_id),
                    action_id=UUID(gap_res.action_id),
                    technique_id=gap_res.technique_id,
                    original_outcome=gap_res.original_outcome,
                    evidence_event_ids=json_lib.dumps(gap_res.evidence_event_ids),
                    matched_rule_ids=json_lib.dumps(gap_res.matched_rule_ids),
                    root_cause=gap_res.root_cause,
                    reason=gap_res.reason,
                    remediation_status="OPEN",
                )
                db_session.add(rec)
                db_session.commit()

        return results

    def propose_candidate_rule(
        self,
        gap_analysis: GapAnalysisResult,
        action: Optional[ActionIR] = None,
        telemetry_events: Optional[List[NormalizedEvent]] = None,
    ) -> CandidateSigmaRule:
        """Derive an evidence-backed CandidateSigmaRule from gap analysis and observed indicators."""
        tech_id = gap_analysis.technique_id
        rule_id = str(uuid4())

        cmd_filter = None
        target_file_filter = None
        proc_filter = None

        if telemetry_events:
            for ev in telemetry_events:
                if ev.TargetFile:
                    target_file_filter = ev.TargetFile
                if ev.CommandLine and ("shadow" in ev.CommandLine or "cat" in ev.CommandLine):
                    cmd_filter = ev.CommandLine
                if ev.ProcessName and ev.ProcessName not in ("bash", "sh"):
                    proc_filter = ev.ProcessName

        if not target_file_filter and action:
            cmd_args = " ".join(action.arguments) if action.arguments else ""
            if "shadow" in cmd_args or "/etc/shadow" in cmd_args:
                target_file_filter = "/etc/shadow"
                cmd_filter = "shadow"
            elif cmd_args:
                cmd_filter = cmd_args

        selection = {}
        if target_file_filter:
            selection["TargetFile|contains"] = target_file_filter
        elif cmd_filter:
            selection["CommandLine|contains"] = cmd_filter
        else:
            selection["CommandLine|contains"] = f"technique_{tech_id}"

        detection = {
            "selection": selection,
            "condition": "selection",
        }


        logsource = {
            "category": "process_creation",
            "product": "linux",
        }

        return CandidateSigmaRule(
            rule_id=rule_id,
            title=f"SentinelForge Detection Rule for {tech_id}",
            description=f"Auto-generated candidate Sigma rule targeting gap action {gap_analysis.action_id} ({tech_id})",
            technique_id=tech_id,
            logsource=logsource,
            detection=detection,
            level="high",
            tags=[f"attack.{tech_id.lower().replace('.', '_')}"],
            references=["https://attack.mitre.org/techniques/" + tech_id.replace(".", "/")],
            source_scenario_id=gap_analysis.scenario_id,
            source_action_ids=[gap_analysis.action_id],
            status="CANDIDATE",
        )



class SigmaRuleValidator:
    """Validates Sigma YAML syntax, required fields, technique metadata, and broad-rule rejection."""

    @staticmethod
    def validate_yaml(rule_yaml: str) -> dict:
        """Parse and validate raw Sigma YAML string."""
        if not rule_yaml or not rule_yaml.strip():
            raise ValueError("Empty or whitespace-only YAML string")

        try:
            parsed = yaml.safe_load(rule_yaml)
        except Exception as exc:
            raise ValueError(f"Malformed YAML syntax: {exc}") from exc

        if not isinstance(parsed, dict):
            raise ValueError("YAML content must evaluate to a dictionary")

        # Required Sigma fields
        for field in ("title", "id", "logsource", "detection"):
            if field not in parsed or not parsed[field]:
                raise ValueError(f"Missing required Sigma field: '{field}'")

        detection = parsed["detection"]
        if not isinstance(detection, dict):
            raise ValueError("Sigma 'detection' field must be a dictionary")

        if "condition" not in detection or not detection["condition"]:
            raise ValueError("Sigma detection block missing 'condition'")

        # Ensure at least one selection dictionary exists
        selections = [v for k, v in detection.items() if k != "condition" and isinstance(v, dict)]
        if not selections:
            raise ValueError("Sigma detection block missing selection criteria")

        # Validate x-sentinelforge provenance
        meta = parsed.get("x-sentinelforge")
        if not isinstance(meta, dict):
            raise ValueError("Missing required 'x-sentinelforge' provenance block")

        for req_meta in ("scenario_id", "action_ids", "technique_id", "rule_id"):
            if req_meta not in meta or not meta[req_meta]:
                raise ValueError(f"Missing provenance field in x-sentinelforge: '{req_meta}'")

        # Reject overly broad rules
        for sel in selections:
            keys = list(sel.keys())
            vals = [str(v).lower().strip() for v in sel.values()]

            # Bare process_name = bash / sh with no other filters is OVERLY BROAD
            if len(keys) == 1 and keys[0].lower() in ("processname", "executable"):
                if vals[0] in ("bash", "sh", "/usr/bin/bash", "/bin/sh", "cmd.exe", "powershell"):
                    raise ValueError(f"Overly broad rule rejected: matching solely on '{keys[0]}={vals[0]}' without specific selection indicators")

        return parsed

    @classmethod
    def validate_candidate_rule(
        cls, rule: CandidateSigmaRule, expected_technique: Optional[str] = None
    ) -> Tuple[bool, str]:
        """Validate a CandidateSigmaRule model for syntax, provenance, and technique match."""
        try:
            yaml_str = rule.to_yaml()
            parsed = cls.validate_yaml(yaml_str)
        except ValueError as exc:
            return False, str(exc)

        rule_tech = str(rule.technique_id).strip().upper()
        if expected_technique:
            exp_tech = str(expected_technique).strip().upper()
            if not (rule_tech == exp_tech or rule_tech.startswith(exp_tech) or exp_tech.startswith(rule_tech)):
                return (
                    False,
                    f"Technique mismatch: candidate rule technique '{rule_tech}' does not match expected gap technique '{exp_tech}'",
                )

        if not rule.source_scenario_id or not rule.source_action_ids:
            return False, "Missing provenance: source_scenario_id or source_action_ids is empty"

        return True, "Candidate Sigma rule syntax, technique, and provenance valid"


class RuleValidationSandbox:
    """Evaluates candidate Sigma rules against malicious and benign telemetry in a controlled sandbox.

    OPERATES STRICTLY ON TELEMETRY IN-MEMORY. DOES NOT EXECUTE COMMANDS.
    """

    def validate_candidate_rule(
        self,
        rule: CandidateSigmaRule,
        malicious_events: List[NormalizedEvent],
        benign_events: List[NormalizedEvent],
        expected_technique: Optional[str] = None,
    ) -> ValidationSandboxResult:
        """Validate candidate rule against malicious telemetry (must detect) and benign telemetry (must not trigger)."""
        now = datetime.now(timezone.utc)

        # 1. Structural & provenance validation
        is_valid, err_msg = SigmaRuleValidator.validate_candidate_rule(
            rule, expected_technique=expected_technique or rule.technique_id
        )
        if not is_valid:
            return ValidationSandboxResult(
                rule_id=rule.rule_id,
                status=ValidationSandboxStatus.REJECTED,
                malicious_passed=False,
                benign_passed=False,
                reason=f"Validation failed: {err_msg}",
                evaluated_at=now,
            )

        # 2. In-memory SigmaEngine testing setup
        engine = SigmaEngine()
        engine.load_rule_from_yaml(rule.to_yaml(), rule.rule_id, rule.technique_id)

        # 3. Test malicious telemetry (MUST MATCH)
        malicious_detected = False
        for ev in malicious_events:
            if not isinstance(ev, NormalizedEvent):
                continue
            res_list = engine.evaluate(ev.to_sigma_dict(), event_id=ev.event_id)
            if any(r.matched for r in res_list):
                malicious_detected = True
                break

        if not malicious_detected:
            return ValidationSandboxResult(
                rule_id=rule.rule_id,
                status=ValidationSandboxStatus.REJECTED,
                malicious_passed=False,
                benign_passed=True,
                reason="MALICIOUS_DETECTION_FAILED: Candidate rule failed to detect target malicious telemetry",
                evaluated_at=now,
            )

        # 4. Test benign telemetry (MUST NOT TRIGGER)
        benign_triggered = False
        for ev in benign_events:
            if not isinstance(ev, NormalizedEvent):
                continue
            res_list = engine.evaluate(ev.to_sigma_dict(), event_id=ev.event_id)
            if any(r.matched for r in res_list):
                benign_triggered = True
                break

        if benign_triggered:
            return ValidationSandboxResult(
                rule_id=rule.rule_id,
                status=ValidationSandboxStatus.REJECTED,
                malicious_passed=True,
                benign_passed=False,
                reason="FALSE_POSITIVE_DETECTED: Candidate rule triggered on benign baseline telemetry",
                evaluated_at=now,
            )

        # 5. Both malicious and benign passed!
        return ValidationSandboxResult(
            rule_id=rule.rule_id,
            status=ValidationSandboxStatus.ACCEPTED,
            malicious_passed=True,
            benign_passed=True,
            reason="Candidate rule passed malicious detection and false-positive immunity sandbox evaluation",
            evaluated_at=now,
        )


class RetestOrchestrator:
    """Prepares and executes authorized retesting of candidate detection rules using the existing security architecture."""

    def prepare_retest(
        self,
        scenario_id: Union[str, UUID],
        gap_action_ids: List[str],
        candidate_rules: List[CandidateSigmaRule],
        validation_result: ValidationSandboxResult,
        technique_ids: Optional[List[str]] = None,
        retest_reason: str = "Authorized retest following candidate rule validation",
    ) -> RetestRequest:
        """Create a RetestRequest ONLY IF candidate rule validation is ACCEPTED."""
        if validation_result.status != ValidationSandboxStatus.ACCEPTED:
            raise ValueError(
                f"Cannot prepare RetestRequest for candidate rule: validation status is {validation_result.status.value} ({validation_result.reason})"
            )

        if not candidate_rules:
            raise ValueError("Cannot prepare RetestRequest with no candidate rules")

        for rule in candidate_rules:
            if not rule.source_scenario_id or not rule.source_action_ids:
                raise ValueError(f"Candidate rule {rule.rule_id} lacks mandatory x-sentinelforge provenance metadata")

        return RetestRequest(
            retest_id=uuid4(),
            scenario_id=UUID(str(scenario_id)),
            gap_action_ids=gap_action_ids,
            technique_ids=technique_ids or [r.technique_id for r in candidate_rules],
            candidate_rules=candidate_rules,
            validation_result=validation_result,
            retest_reason=retest_reason,
            timestamp=datetime.now(timezone.utc),
        )

    def execute_retest(
        self,
        retest_request: RetestRequest,
        objective: SecurityObjective,
        red_planner: RedAgentPlanner,
        adapter: SimulationAdapter,
        sigma_engine: SigmaEngine,
        gap_evaluator: DetectionGapEvaluator,
        before_outcome: ScenarioDetectionOutcome,
        strategy_type: str = "credential_dump_shadow",
    ) -> RetestResult:
        """Execute retest through RedAgentPlanner -> SafetyBoundary -> PolicyEngine -> SignedBlueprint -> SimulationAdapter -> Telemetry -> DetectionGapEvaluator."""
        # 1. Register validated candidate rules into SigmaEngine
        for rule in retest_request.candidate_rules:
            sigma_engine.load_rule_from_yaml(rule.to_yaml(), rule.rule_id, rule.technique_id)

        # 2. Re-plan scenario through RedAgentPlanner (runs SafetyBoundary & PolicyEngine)
        plan_res: PlanResult = red_planner.plan_scenario(objective=objective, strategy_type=strategy_type)
        if not plan_res.is_allowed:
            now = datetime.now(timezone.utc)
            return RetestResult(
                retest_id=retest_request.retest_id,
                organization_id=objective.organization_id,
                scenario_id=retest_request.scenario_id,
                before_outcome=before_outcome.overall_outcome.value if isinstance(before_outcome.overall_outcome, DetectionOutcome) else str(before_outcome.overall_outcome),
                after_outcome=DetectionOutcome.DETECTION_GAP.value,
                detection_improved=False,
                validated_rule_ids=[],
                evaluated_at=now,
            )

        # 3. Execute via SimulationAdapter (authorized execution)
        sim_events: List[NormalizedEvent] = []
        scenario_id_str = str(plan_res.scenario.scenario_id)

        for action_ir in plan_res.actions:
            exit_code, stdout_bytes, stderr_bytes, truncated, timed_out = adapter.execute_bounded(
                executable=action_ir.executable,
                arguments=action_ir.arguments,
                run_as_user=action_ir.run_as_user,
                timeout=getattr(action_ir, "max_execution_seconds", 30),
            )


            stdout_text = stdout_bytes.decode("utf-8", errors="replace")
            cmd_line = " ".join(action_ir.arguments) if action_ir.arguments else action_ir.executable

            norm_event = NormalizedEvent(
                event_id=str(uuid4()),
                correlation_id=scenario_id_str,
                timestamp=datetime.now(timezone.utc).isoformat() + "Z",
                source="linux_auditd",
                EventType="execve",
                ProcessName=action_ir.executable.split("/")[-1],
                Executable=action_ir.executable,
                CommandLine=cmd_line,
                UserName=action_ir.run_as_user,
                UserUid=1000 if action_ir.run_as_user == "labuser" else 0,
                TargetFile="/etc/shadow" if "shadow" in cmd_line else None,
                ContainerName="sentinelforge-target",
                ContainerId="container_123",
                ParentProcess="bash",
                raw_event_hash=str(hash(cmd_line + str(exit_code))),
            )
            sim_events.append(norm_event)


        # 4. Evaluate retest telemetry with DetectionGapEvaluator
        after_outcome = gap_evaluator.evaluate_scenario(
            scenario_id=plan_res.scenario.scenario_id,
            actions=plan_res.actions,
            events=sim_events,
            sigma_engine=sigma_engine,
            organization_id=objective.organization_id,
        )

        before_str = (
            before_outcome.overall_outcome.value
            if isinstance(before_outcome.overall_outcome, DetectionOutcome)
            else str(before_outcome.overall_outcome)
        )
        after_str = (
            after_outcome.overall_outcome.value
            if isinstance(after_outcome.overall_outcome, DetectionOutcome)
            else str(after_outcome.overall_outcome)
        )

        # Detection improved iff BEFORE was failure AND AFTER is DETECTED AND candidate rule matched
        candidate_rule_ids = {r.rule_id for r in retest_request.candidate_rules}
        matched_in_after = set()
        for act_out in after_outcome.action_outcomes:
            matched_in_after.update(act_out.matched_rule_ids)

        candidate_rule_responsible = bool(candidate_rule_ids.intersection(matched_in_after))

        detection_improved = (
            before_str in (DetectionOutcome.DETECTION_GAP.value, DetectionOutcome.NOT_DETECTED.value)
            and after_str == DetectionOutcome.DETECTED.value
            and candidate_rule_responsible
        )

        return RetestResult(
            retest_id=retest_request.retest_id,
            organization_id=objective.organization_id,
            scenario_id=plan_res.scenario.scenario_id,
            before_outcome=before_str,
            after_outcome=after_str,
            detection_improved=detection_improved,
            validated_rule_ids=list(candidate_rule_ids.intersection(matched_in_after)),
            evaluated_at=datetime.now(timezone.utc),
        )
