from enum import Enum

class SecurityRejectionCode(str, Enum):
    POLICY_DENIED = "POLICY_DENIED"
    INVALID_ACTION_IR = "INVALID_ACTION_IR"
    INVALID_TARGET = "INVALID_TARGET"
    INVALID_EXECUTABLE = "INVALID_EXECUTABLE"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    UNAUTHORIZED_USER = "UNAUTHORIZED_USER"
    EXPIRED_BLUEPRINT = "EXPIRED_BLUEPRINT"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    TAMPERED_BLUEPRINT = "TAMPERED_BLUEPRINT"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    # Branch 2: Application Remediation
    PRODUCTION_TARGET_NO_REMEDIATION = "PRODUCTION_TARGET_NO_REMEDIATION"
    REMEDIATION_POLICY_VIOLATION = "REMEDIATION_POLICY_VIOLATION"
    CLONE_CREATION_FAILED = "CLONE_CREATION_FAILED"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    REMEDIATION_BUDGET_EXHAUSTED = "REMEDIATION_BUDGET_EXHAUSTED"

class SecurityRejection(Exception):
    def __init__(self, code: SecurityRejectionCode, message: str, entity_id: str = None):
        self.code = code
        self.message = message
        self.entity_id = entity_id
        super().__init__(f"[{code.value}] {message}")
